namespace Minsk.CodeAnalysis.Syntax
{
    public enum SyntaxKind
    {
        BadToken,
        //Trivia
        SkippedTextTrivia,
        WhitespaceTrivia,
        MultiLineCommentTrivia,
        SingleLineCommentTrivia,
        LineBreakTrivia,

        //Tokens
        EndOfFileToken,
        NumberToken,
        PlusToken,
        MinusToken,
        StarToken,
        SlashToken,
        OpenParenthesisToken,
        CloseParenthesisToken,
        IdentifierToken,
        BangToken,
        AmpersandToken,
        AmpersandAmpersandToken,
        PipeToken,
        PipePipeToken,
        EqualsEqualsToken,
        BangEqualsToken,
        EqualsToken,
        OpenBraceToken,
        CloseBraceToken,
        GreaterToken,
        GreaterOrEqualsToken,
        LessOrEqualsToken,
        LessToken,
        TildeToken,
        HatToken,
        StringToken,
        CommaToken,
        ColonToken,

        //Keyword
        TrueKeyword,
        FalseKeyword,
        LetKeyword,
        VarKeyword,
        IfKeyword,
        ElseKeyword,
        WhileKeyword,
        ForKeyword,
        ToKeyword,
        FunctionKeyword,
        DoKeyword,
        ContinueKeyword,
        BreakKeyword,
        ReturnKeyword,

        //Nodes
        CompilationUnit,
        ElseClause,
        TypeClause,
        GlobalStatement,
        FunctionDeclaration,
        Parameter,

        //Statements
        BlockStatement,
        VariableDeclaration,
        ExpressionStatement,
        IfStatement,
        WhileStatement,
        ForStatement,
        DoWhileStatement,
        ContinueStatement,
        BreakStatement,
        ReturnStatement,

        //Expressions
        LiteralExpression,
        BinaryExpression,
        ParenthesisExpression,
        UnaryExpression,
        AssignmentExpression,
        NameExpression,
        CallExpression,
    }
}